/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package old;



import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import jdbc.DbAdapter;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.FadingUtils;
import net.java.balloontip.utils.TimingUtils;
import swinghacks.MoveMouseListener;

/**
 *
 * @author mars
 */
public class Login extends javax.swing.JFrame {

    private final Border borderline;
    private Font tfont;
    private Graphics g;
    private final String image = "/home/mars/NetBeansProjects/HPMIS/src/images/users.jpeg";
    private final String headerImage = "/home/mars/NetBeansProjects/HPMIS/src/images/footer.png";
    private final String borderText = "Login";
    private Connection conn = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;

    /**
     * Creates new form Login
     */
    public Login() {
        super("Login");
        getContentPane().setBackground(Color.WHITE);
        Color color = new Color(255, 0, 0);
        borderline = BorderFactory.createLineBorder(Color.red, 1, true);
        tfont = new Font("SERIF", Font.BOLD, 15);
        initComponents();
        // lblHeaderImage.setIcon(new ImageIcon(headerImage));
        loginPanel.setBorder(new TitledBorder(borderline, borderText, TitledBorder.LEADING, TitledBorder.CENTER, tfont, Color.RED));
        loginPanel.setBackground(Color.WHITE);

        lblPassword.setForeground(Color.RED);
        lblUsername.setForeground(Color.RED);
        lblPassword.setFont(tfont);
        lblUsername.setFont(tfont);
        lblLoginUserIcon.setText("");
        lblLoginUserIcon.setIcon(new ImageIcon(image));

        userCombo.setForeground(Color.RED);
        userCombo.setFont(tfont);

        userLevelComboTxt.setBackground(Color.WHITE);
        userLevelComboTxt.setForeground(Color.RED);
        userLevelComboTxt.setFont(tfont);

        tfUsername.setForeground(Color.red);
        tfPassword.setForeground(Color.red);

        btnLogin.setFont(tfont);
        btnLogin.setForeground(Color.RED);
        btnCancel.setFont(tfont);
        btnCancel.setForeground(Color.RED);
        btnLogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent event) {
                btnLogin.setBackground(Color.WHITE);
                btnLogin.setForeground(Color.BLUE);
                btnLogin.setFont(tfont);
                btnLogin.setToolTipText("Press To Login");
            }

            @Override
            public void mouseExited(MouseEvent event) {
                btnLogin.setForeground(Color.RED);
            }

            @Override
            public void mouseClicked(MouseEvent event) {
                validateUserLogin();
            }
        });
        btnCancel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent event) {
                btnCancel.setBackground(Color.WHITE);
                btnCancel.setForeground(Color.BLUE);
                btnCancel.setFont(tfont);
                btnCancel.setToolTipText("Press To Cancel");
            }

            @Override
            public void mouseExited(MouseEvent event) {
                btnCancel.setForeground(Color.RED);
            }
        });
        btnCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                System.exit(0);
            }
        });
        MoveMouseListener mml = new MoveMouseListener((JComponent) getContentPane(), this);
        getContentPane().addMouseListener(mml);
        getContentPane().addMouseMotionListener(mml);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        userLevelComboTxt = new javax.swing.JComboBox();
        tfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        userCombo = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblLoginUserIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsername.setText("Username");

        userLevelComboTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Counsellor", "Doctor", "Health Care Attendant" }));

        lblPassword.setText("Password");

        userCombo.setText("UserLevel");

        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(userCombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(tfPassword)
                    .addComponent(tfUsername)
                    .addComponent(userLevelComboTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCombo)
                    .addComponent(userLevelComboTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancel))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblLoginUserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLoginUserIcon)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void validateUserLogin() {
        try {
            conn = DbAdapter.ConnectDb();
            String username = tfUsername.getText();
            String password = tfPassword.getText();
            if (username.equals("") && password.equals("")) {
                RoundedBalloonStyle roundballoontip = new RoundedBalloonStyle(15, 5, Color.RED, Color.WHITE);
                BalloonTip balloonTip = new BalloonTip(btnLogin, "Some fields are empty", roundballoontip, false);
                //TimingUtils.showTimedBalloon(balloonTip, 300);
                FadingUtils.fadeInBalloon(balloonTip, getActionListener(balloonTip), 100, 24);
            } else {

                // String sql = "select * from login where USERNAME=? and PASSWORD=?";
                String sql = "insert into login(username,password)values (?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, password);
                pst.executeUpdate();
                rs = pst.executeQuery();
                if (rs.next()) {
                    RoundedBalloonStyle roundballoontip = new RoundedBalloonStyle(15, 5, Color.RED, Color.WHITE);
                    BalloonTip balloonTip = new BalloonTip(btnLogin, "You are logged in as " + userLevelComboTxt.getSelectedItem().toString(), roundballoontip, false);
                    TimingUtils.showTimedBalloon(balloonTip, 100);
//FadingUtils.fadeInBalloon(balloonTip, userLevelComboTxt, 100, 24);
                    PatientRegistration patient = new PatientRegistration();
                    patient.setVisible(true);
                } else {
                    RoundedBalloonStyle roundballoontip = new RoundedBalloonStyle(15, 5, Color.RED, Color.WHITE);
                    BalloonTip balloonTip = new BalloonTip(btnLogin, "Username and Password not correct", roundballoontip, false);
                    TimingUtils.showTimedBalloon(balloonTip, 100);
                    // FadingUtils.fadeInBalloon(balloonTip, userLevelComboTxt, 100, 24);
                }
            }
        } catch (SQLException e) {

        }
    }

    private ActionListener getActionListener(final BalloonTip balloontip) {
        ActionListener fadeInListener = new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                TimingUtils.showTimedBalloon(balloontip, 300);
            }
        };
        return fadeInListener;
    }
    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setCursor(java.awt.Cursor.getPredefinedCursor(HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setCursor(java.awt.Cursor.getPredefinedCursor(HAND_CURSOR));
        // com.sal.gen.Gen.setHandCursor(btnCancel);
//          com.sal.gen.FileDrop fileDrop = new com.sal.gen.FileDrop;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLoginUserIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel userCombo;
    private javax.swing.JComboBox userLevelComboTxt;
    // End of variables declaration//GEN-END:variables
}
